Chapter 11/taskmanager/accounts/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        views.CustomLoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            success_url=reverse_lazy("accounts:password_change_done"),
            template_name="accounts/password_change_form.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            success_url=reverse_lazy("accounts:password_reset_done"),
            email_template_name="accounts/custom_password_reset_email.html",
            template_name="accounts/password_reset_form.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm_form.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("show-api-token/", views.token_generation_view, name="api-token"),
]

Chapter 11/taskmanager/tasks/urls.py
from django.urls import path, register_converter
from django.views.generic import TemplateView

from . import converters
from .views import (
    ContactFormView,
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
    create_task_on_sprint,
    manage_epic_tasks,
    task_by_date,
    task_home,
)

app_name = "tasks"
register_converter(converters.DateConverter, "yyyymmdd")
handler404 = "tasks.views.custom_404"


urlpatterns = [
    path("", task_home, name="task-home"),
    path("contact/", ContactFormView.as_view(), name="contact"),
    path(
        "contact-success/",
        TemplateView.as_view(template_name="tasks/contact_success.html"),
        name="contact-success",
    ),
    path("help/", TemplateView.as_view(template_name="tasks/help.html"), name="help"),
    path("tasks/", TaskListView.as_view(), name="task-list"),  # GET
    path("tasks/new/", TaskCreateView.as_view(), name="task-create"),  # POST
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),  # GET
    path(
        "tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task-update"
    ),  # PUT/PATCH
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),  # DELETE
    path("tasks/<yyyymmdd:date>/", task_by_date, name="task-get-by-date"),
    path(
        "tasks/sprint/add_task/<int:pk>/",
        create_task_on_sprint,
        name="task-add-to-sprint",
    ),
    path("epic/<int:epic_pk>/", manage_epic_tasks, name="task-batch-create"),
]

Chapter 11/taskmanager/tasks/models.py
from django.conf import settings
from django.db import models
from tasks.enums import TaskStatus


class VersionMixing:
    version = models.IntegerField(default=0)


class Task(models.Model, VersionMixing):
    STATUS_CHOICES = [
        (status.value, status.name.replace("_", " ").title()) for status in TaskStatus
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=False, default="")
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=TaskStatus.UNASSIGNED.value,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="created_tasks",
        on_delete=models.CASCADE,
        null=False,
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="owned_tasks",
        on_delete=models.SET_NULL,
        null=True,
    )
    version = models.IntegerField(default=0)
    file_upload = models.FileField(upload_to="tasks/files/", null=True, blank=True)
    image_upload = models.ImageField(upload_to="tasks/images/", null=True, blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(status="UNASSIGNED")
                | models.Q(status="IN_PROGRESS")
                | models.Q(status="DONE")
                | models.Q(status="ARCHIVED"),
                name="status_check",
            ),
        ]
        permissions = [
            ("custom_task", "Custom Task Permission"),
        ]


class Epic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="created_epics", on_delete=models.CASCADE
    )
    tasks = models.ManyToManyField("Task", related_name="epics", blank=True)
    # This field might be used to denote the progress of the epic
    completion_status = models.FloatField(default=0.0)


class Sprint(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="created_sprints",
        on_delete=models.CASCADE,
    )
    tasks = models.ManyToManyField("Task", related_name="sprints", blank=True)
    # The epic to which this sprint is contributing
    epic = models.ForeignKey(
        Epic, related_name="sprints", on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(end_date__gt=models.F("start_date")),
                name="end_date_after_start_date",
            ),
        ]


class Email(models.Model):
    email = models.EmailField()
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="watchers")


class FormSubmission(models.Model):
    uuid = models.UUIDField(unique=True)

Chapter 11/taskmanager/tasks/forms.py
import uuid

from django import forms
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.forms import modelformset_factory
from tasks.fields import EmailsListField

from .models import Email, FormSubmission, Task


class TaskFormWithModel(forms.ModelForm):
    uuid = forms.UUIDField(required=False, widget=forms.HiddenInput())

    watchers = EmailsListField(required=False)

    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "status",
            "watchers",
            "file_upload",
            "image_upload",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Check if an instance is provided and populate watchers field
        if self.instance and self.instance.pk:
            self.fields["watchers"].initial = ", ".join(
                email.email for email in self.instance.watchers.all()
            )
        self.fields["uuid"].initial = uuid.uuid4()

    def clean_uuid(self):
        uuid_value = self.cleaned_data.get("uuid")

        with transaction.atomic():
            # Try to record the form submission by UUID
            try:
                FormSubmission.objects.create(uuid=uuid_value)
            except IntegrityError:
                # The UUID already exists, so the form was already submitted
                raise ValidationError("This form has already been submitted.")

        return uuid_value

    def save(self, commit=True):
        # First, save the Task instance
        task = super().save(commit)

        # If commit is True, save the associated emails
        if commit:
            # First, remove the old emails associated with this task
            task.watchers.all().delete()

            # Add the new emails to the Email model
            for email_str in self.cleaned_data["watchers"]:
                Email.objects.create(email=email_str, task=task)

        return task


class TaskFormWithRedis(forms.ModelForm):
    uuid = forms.UUIDField(required=False, widget=forms.HiddenInput())
    watchers = EmailsListField(required=False)

    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "status",
            "watchers",
            "file_upload",
            "image_upload",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields["watchers"].initial = ", ".join(
                email.email for email in self.instance.watchers.all()
            )
        self.fields["uuid"].initial = uuid.uuid4()

    def clean_uuid(self):
        uuid_value = str(self.cleaned_data.get("uuid"))
        was_set = cache.set(uuid_value, "submitted", nx=True)
        if not was_set:
            # If 'was_set' is False, the UUID already exists in the cache.
            # This indicates a duplicate form submission.
            raise ValidationError("This form has already been submitted.")
        return uuid_value


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)


EpicFormSet = modelformset_factory(Task, form=TaskFormWithRedis, extra=0)

Chapter 11/taskmanager/tasks/views.py
from collections import defaultdict
from datetime import date

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import (
    Http404,
    HttpRequest,
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from tasks.forms import ContactForm, EpicFormSet, TaskFormWithRedis

from . import services
from .mixins import SprintTaskMixin
from .models import Task


class TaskListView(PermissionRequiredMixin, ListView):
    permission_required = ("tasks.view_task", "tasks.custom_task")

    model = Task
    template_name = "task_list.html"
    context_object_name = "tasks"
    login_url = "accounts/login/"
    raise_exception = True


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/task_detail.html"
    context_object_name = "task"


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/task_form.html"
    form_class = TaskFormWithRedis

    def get_success_url(self):
        return reverse_lazy("tasks:task-detail", kwargs={"pk": self.object.id})

    def form_valid(self, form):
        # Set the creator to the currently logged in user
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TaskUpdateView(PermissionRequiredMixin, SprintTaskMixin, UpdateView):
    permission_required = ("tasks.change_task",)

    model = Task
    template_name = "tasks/task_form.html"
    form_class = TaskFormWithRedis

    def get_success_url(self):
        return reverse_lazy("tasks:task-detail", kwargs={"pk": self.object.id})

    def has_permission(self):
        # First, check if the user has the general permission to edit tasks
        has_general_permission = super().has_permission()

        # Then check if the user is either the
        # creator or the owner of this task
        task_id = self.kwargs.get("pk")
        task = get_object_or_404(Task, id=task_id)

        is_creator_or_owner = (
            task.creator == self.request.user or task.owner == self.request.user
        )

        # Return True only if both conditions are met
        return has_general_permission and is_creator_or_owner


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/task_confirm_delete.html"
    success_url = reverse_lazy("tasks:task-list")


@login_required
def task_home(request):
    # Fetch all tasks at once
    tasks = Task.objects.filter(
        status__in=["UNASSIGNED", "IN_PROGRESS", "DONE", "ARCHIVED"]
    )

    # Initialize dictionaries to hold tasks by status
    context = defaultdict(list)

    # Categorize tasks into their respective lists
    for task in tasks:
        if task.status == "UNASSIGNED":
            context["unassigned_tasks"].append(task)
        elif task.status == "IN_PROGRESS":
            context["in_progress_tasks"].append(task)
        elif task.status == "DONE":
            context["done_tasks"].append(task)
        elif task.status == "ARCHIVED":
            context["archived_tasks"].append(task)

    return render(request, "tasks/home.html", context)


@login_required
def task_by_date(request: HttpRequest, by_date: date) -> HttpResponse:
    template = loader.get_template("task_list.html")
    tasks = services.get_task_by_date(by_date)
    context = {"tasks": tasks}  # data to inject into the template
    html = template.render(context, request)
    return HttpResponse(html)


@permission_required("tasks.add_task")
def create_task_on_sprint(request: HttpRequest, sprint_id: int) -> HttpResponseRedirect:
    if request.method == "POST":
        task_data: dict[str, str] = {
            "title": request.POST["title"],
            "description": request.POST.get("description", ""),
            "status": request.POST.get("status", "UNASSIGNED"),
        }
        task = services.create_task_and_add_to_sprint(
            task_data, sprint_id, request.user
        )
        return redirect("tasks:task-detail", task_id=task.id)
    raise Http404("Not found")


@login_required
def claim_task_view(request, task_id):
    user_id = (
        request.user.id
    )  # Assuming you have access to the user ID from the request

    try:
        services.claim_task(user_id, task_id)
        return JsonResponse({"message": "Task successfully claimed."})
    except Task.DoesNotExist:
        return HttpResponse("Task does not exist.", status=404)
    except services.TaskAlreadyClaimedException:
        return HttpResponse("Task is already claimed or completed.", status=400)


def custom_404(request, exception):
    return render(request, "404.html", {}, status=404)


class ContactFormView(FormView):
    template_name = "tasks/contact_form.html"
    form_class = ContactForm
    success_url = reverse_lazy("tasks:contact-success")

    def form_valid(self, form):
        subject = form.cleaned_data.get("subject")
        message = form.cleaned_data.get("message")
        from_email = form.cleaned_data.get("from_email")

        # You can use Django's send_mail function,
        # here is a simple example that sends the message to your email.
        # Please update 'your-email@example.com' with your email and configure
        # the EMAIL settings in your Django settings file
        services.send_contact_email(
            subject, message, from_email, ["your-email@example.com"]
        )

        return super().form_valid(form)


@login_required
def manage_epic_tasks(request, epic_pk):
    epic = services.get_epic_by_id(epic_pk)
    if not epic:
        raise Http404("Epic does not exist")
    if request.method == "POST":
        formset = EpicFormSet(request.POST, queryset=services.get_tasks_for_epic(epic))
        if formset.is_valid():
            tasks = formset.save(commit=False)
            services.save_tasks_for_epic(epic, tasks)
            formset.save_m2m()  # handle many-to-many relations if there are any
            return redirect("tasks:task-list")
    else:
        formset = EpicFormSet(queryset=services.get_tasks_for_epic(epic))

    return render(request, "tasks/manage_epic.html", {"formset": formset, "epic": epic})

Chapter 11/taskmanager/templates/tasks/_footer.html
<footer class="footer mt-auto py-3 bg-light text-center">
    <div class="container">
        <a href="{% url 'tasks:help' %}" class="text-dark">Help</a> |
        <a href="{% url 'tasks:contact' %}" class="text-dark">Contact</a>
    </div>
</footer>

Chapter 11/taskmanager/templates/tasks/_header.html
{% load static %}

<header class="d-flex justify-content-between align-items-center p-3">
    <!-- Left side -->
    <div class="d-flex align-items-center">
        <!-- Logo -->
        <img src="{% static 'images/logo.png' %}" alt="Task Manager" width="50" class="mr-3">

        <a href="{% url 'tasks:task-home' %}" class="btn btn-secondary mr-2" role="button">Home</a>
        <a href="{% url 'tasks:task-create' %}" class="btn btn-primary" role="button">Create</a>
    </div>

    <!-- Right side -->
    <div class="d-flex align-items-center">
        <input type="text" class="form-control" id="search" placeholder="Search">
        <button type="button" class="btn btn-success ml-2">Search</button>

        <!-- Login/Logout links -->
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger ml-2" role="button">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-info ml-2" role="button">Login</a>
        {% endif %}
    </div>
</header>

Chapter 11/taskmanager/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	{# Using a block for the title allows child templates to provide their specific titles. We use the default filter to set a fallback title if not provided. #}
	<title>{% block title %}{{ page_title|default:"Default Title" }}{% endblock %}</title>

	{# This block is intended for page-specific CSS. Override in child templates as needed. #}
	{% block extra_css %}{% endblock %}

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
	{# Use of the 'include' tag helps in modularizing the HTML, making maintenance easier by breaking the layout into smaller parts. #}
	{% include "tasks/_header.html" %}
    <main class="d-flex flex-column justify-content-center align-items-center"></main>
        <div class="text-center">
			{# Main content block can be overridden in child templates to provide page-specific content. #}
            {% block content %}
            {% endblock %}
        </div>
    </main>
    {% include "tasks/_footer.html" %}
	{# A block for adding custom JavaScript ensures flexibility for child templates to introduce or override scripts. #}
	{% block extra_javascript %}{% endblock %}
    <!-- JS files -->
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <!-- <script src="script.js"></script> -->
</body>
</html>

Chapter 11/taskmanager/templates/tasks/contact_form.html
{% extends "tasks/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="w-50">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Contact Us!</h2>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'tasks:contact' %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                            {{ field|add_class:"form-control" }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary w-100">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/contact_success.html
{% extends "tasks/base.html" %}

{% block content %}
  <div class="container">
    <h1>Contact Message Sent!</h1>
    <p>Thank you for reaching out! We have received your message and will respond as soon as possible.</p>
    <a href="{% url 'tasks:task-home' %}">Return Home</a>
  </div>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/help.html
{% extends "tasks/base.html" %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                Help Page
            </div>
            <div class="card-body">
                <h5 class="card-title">What is a task manager?</h5>
                <p class="card-text">A task management system is software that helps users organize and track the progress of tasks.</p>
            </div>
        </div>
    </div>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/home.html
{% extends "tasks/base.html" %}

{% block content %}
    <div class="container mt-5">
        <h2>Tasks by Status</h2>
        <div class="row mt-4">

            <!-- Unassigned Tasks -->
            <div class="col-md-3">
                <h4>Unassigned</h4>
                {% for task in unassigned_tasks %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a></h5>
                            <p class="card-text">Owner: {{ task.owner.username|default:"None" }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- In Progress Tasks -->
            <div class="col-md-3">
                <h4>In Progress</h4>
                {% for task in in_progress_tasks %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a></h5>
                            <p class="card-text">Owner: {{ task.owner.username|default:"None" }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- Completed Tasks -->
            <div class="col-md-3">
                <h4>Completed</h4>
                {% for task in done_tasks %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a></h5>
                            <p class="card-text">Owner: {{ task.owner.username|default:"None" }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div> <!-- End of row -->


    </div> <!-- End of container -->
{% endblock %}

Chapter 11/taskmanager/templates/tasks/manage_epic.html
{% extends "tasks/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-5">
    <h1>Epic: {{epic.name}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}

        <div class="row">
            {% for form in formset %}
            <div class="col-md-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field|add_class:"form-control" }}
                            {% if field.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in field.errors %}
                                <p class="mb-0">{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/task_confirm_delete.html
{% extends "tasks/base.html" %}

{% block content %}
<div class="vh-100 d-flex justify-content-center align-items-center">
    <div class="text-center w-50">  <!-- Use w-50 for 50% width or adjust as needed -->
        <h1 class="mb-3">Delete Task</h1>
        <p class="mb-4">Are you sure you want to delete the task "{{ task.name }}"?</p>

        <form method="post" class="mb-3">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, delete</button>
        </form>

        <a href="{% url 'tasks:task-detail' task.id %}" class="btn btn-secondary">No, take me back</a>
    </div>
</div>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}

{% block content %}
<div class="vh-100 d-flex justify-content-center align-items-center">
    <div class="container text-center">
        <h1 class="mb-4 ">{{ task.title }}</h1>
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Description</h2>
                <p class="card-text">{{ task.description }}</p>

                <!-- Emails list -->
                <h3>Emails</h3>
                <ul class="list-unstyled">
                    {% for watcher in task.watchers.all %}
                    <li>{{ watcher.email }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% if task.file_upload %}
            <a href="{{ task.file_upload.url }}" download>Download File</a>
        {% endif %}

        {% if task.image_upload %}
            <div>
                <img src="{{ task.image_upload.url }}" alt="Task Image" style="max-width: 300px;">
            </div>
        {% endif %}
        <div class="mt-4 d-inline-block">
            <a href="{% url 'tasks:task-update' task.id %}" class="btn btn-primary me-2">Edit</a>
            <a href="{% url 'tasks:task-delete' task.id %}" class="btn btn-danger me-2">Delete</a>
            <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
</div>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/task_form.html
{% extends "tasks/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="w-50">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Create a New Task</h2>
            </div>
            <div class="card-body">
                 <form id="taskForm" method="post" action="{% if task.pk %}{% url 'tasks:task-update' task.pk %}{% else %}{% url 'tasks:task-create' %}{% endif %}">

                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.is_hidden %}
                            {{ field }}
                        {% else %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {% if field.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in field.errors %}
                                <p class="mb-0"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            </div>
                            {% endif %}
                            {{ field|add_class:"form-control" }}
                        </div>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary w-100">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script>
    document.getElementById('taskForm').addEventListener('submit', function(){
        this.querySelector('button[type="submit"]').disabled = true;
    });
</script>
{% endblock %}

Chapter 11/taskmanager/templates/tasks/task_list.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>Task List</h1>
  <ul>
  {% for task in tasks %}
    <li class="list-unstyled">
      <a href="{% url 'tasks:task-detail' task.id %}">{{ task.title }}</a>
    </li>
  {% empty %}
    <li>No tasks available.</li>
  {% endfor %}
  </ul>
{% endblock %}